const LANGUAGES = [
  // Top 20 frist of this list is the most well know languages
  "English",
  "Chinese",
  "Spanish",
  "Hindi",
  "Arabic",
  "Bengali",
  "Portuguese",
  "Russian",
  "Japanese",
  "Punjabi",
  "German",
  "Javanese",
  "Wu",
  "Malay",
  "Telugu",
  "Vietnamese",
  "Korean",
  "French",
  "Marathi",
  "Tamil",
  // The remaining languages are sorted in ascending order
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Cebuano",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "Esperanto",
  "Estonian",
  "Finnish",
  "Frisian",
  "Galician",
  "Georgian",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indonesian",
  "Irish",
  "Italian",
  "Jamaican Creole",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Kirundi",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malayalam",
  "Maltese",
  "Maori",
  "Mongolian",
  "Myanmar (Burmese)",
  "Nepali",
  "Norwegian",
  "Nyanja (Chichewa)",
  "Occitan",
  "Oromo",
  "Pashto",
  "Persian",
  "Polish",
  "Pushto (Pashto)",
  "Romanian",
  "Samoan",
  "Scots Gaelic",
  "Serbian",
  "Sesotho",
  "Shona",
  "Sindhi",
  "Sinhala (Sinhalese)",
  "Slovak",
  "Slovenian",
  "Somali",
  "Southern Sotho",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tagalog (Filipino)",
  "Tajik",
  "Tatar",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Welsh",
  "Western Frisian",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];

const LANGAUGE_LEVEL = [
  "Beginner",
  "Pre-Intermediate",
  "Intermediate",
  "Upper-Intermediate",
  "Advanced",
  "Proficient",
];

const JOINERS = [
  "Crhitiano Ronaldo",
  "Harry Macguire",
  "Lionel Messi",
  "Marcus Rashford",
  "Darwin Nudez",
];

const TOPICS = [
  "Technology",
  "Science",
  "Politics",
  "Entertainment",
  "Music",
  "Art",
  "Food",
  "Travel",
  "Books",
  "Fashion",
  "Sports",
  "Fitness",
  "Health",
  "Education",
  "Business",
  "Finance",
  "Investing",
  "Marketing",
  "Social Media",
  "Gaming",
  "Programming",
  "Web Development",
  "Mobile Development",
  "Artificial Intelligence",
  "Machine Learning",
  "Data Science",
  "Blockchain",
  "Cryptocurrency",
  "Virtual Reality",
  "Augmented Reality",
  "Space Exploration",
];

const ENVS = {
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
};

export { LANGUAGES, JOINERS, LANGAUGE_LEVEL, TOPICS, ENVS };
